# Generated by Django 4.2.1 on 2023-07-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sms_enabled',
            field=models.BooleanField(default=0),
        ),
    ]
