# Generated by Django 4.2.1 on 2023-07-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
