# Generated by Django 4.2.1 on 2023-07-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0004_profile_sms_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
